# Generated by Django 5.1.7 on 2025-04-12 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0002_examsupervisionassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSurveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.OneToOneField(help_text='The exam being supervised.', on_delete=django.db.models.deletion.CASCADE, related_name='surveillance_assignment', to='Acadimic.exam')),
                ('teacher', models.ForeignKey(blank=True, help_text='The teacher assigned to supervise this exam.', limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveillance_duties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['exam__exam_date', 'teacher'],
                'unique_together': {('exam', 'teacher')},
            },
        ),
        migrations.DeleteModel(
            name='ExamSupervisionAssignment',
        ),
    ]
