# Generated by Django 5.1.7 on 2025-04-12 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0002_basemodule_promo_semester_speciality_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionmodule',
            name='version_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ExamPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_periods', to='Acadimic.semester')),
            ],
        ),
    ]
