# Generated by Django 5.1.7 on 2025-04-12 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0003_alter_versionmodule_version_name_examperiod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemodule',
            name='code',
        ),
        migrations.RemoveField(
            model_name='basemodule',
            name='coef',
        ),
        migrations.AlterUniqueTogether(
            name='versionmodule',
            unique_together={('base_module', 'version_name')},
        ),
        migrations.AddField(
            model_name='basemodule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='promos', to='Acadimic.versionmodule'),
        ),
        migrations.AddField(
            model_name='versionmodule',
            name='coefficient',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='versionmodule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='versionmodule',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_modules', to='Acadimic.semester'),
        ),
        migrations.AlterField(
            model_name='versionmodule',
            name='version_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='versionmodule',
            name='cours_hours',
        ),
        migrations.RemoveField(
            model_name='versionmodule',
            name='td_hours',
        ),
        migrations.RemoveField(
            model_name='versionmodule',
            name='tp_hours',
        ),
    ]
