# Generated by Django 5.1.7 on 2025-04-12 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0003_examsurveillance_delete_examsupervisionassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examsurveillance',
            options={'ordering': ['exam__exam_date', 'teacher'], 'verbose_name': 'Exam Surveillance Assignment', 'verbose_name_plural': 'Exam Surveillance Assignments'},
        ),
        migrations.AlterField(
            model_name='examsurveillance',
            name='exam',
            field=models.ForeignKey(help_text='The exam being supervised.', on_delete=django.db.models.deletion.CASCADE, related_name='surveillance_assignments', to='Acadimic.exam'),
        ),
    ]
