# Generated by Django 5.1.7 on 2025-04-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0004_remove_basemodule_code_remove_basemodule_coef_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionmodule',
            name='cours_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='versionmodule',
            name='td_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='versionmodule',
            name='tp_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
