# Generated by Django 5.1.7 on 2025-04-12 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0004_alter_examsurveillance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['semester', 'section', 'exam_date']},
        ),
        migrations.AddField(
            model_name='exam',
            name='section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='Acadimic.section'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('semester', 'module', 'section')},
        ),
    ]
