# Generated by Django 5.1.7 on 2025-04-13 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def create_default_promo(apps, schema_editor):
    Speciality = apps.get_model('Acadimic', 'Speciality')
    Promo = apps.get_model('Acadimic', 'Promo')
    
    # Create default speciality if it doesn't exist
    speciality, _ = Speciality.objects.get_or_create(name='Default Speciality')
    
    # Create default promo if it doesn't exist
    promo, _ = Promo.objects.get_or_create(
        name='Default Promo',
        defaults={
            'speciality': speciality,
            'year_start': 2024,
            'year_end': 2025
        }
    )
    return promo

def update_semester_promo(apps, schema_editor):
    Semester = apps.get_model('Acadimic', 'Semester')
    Promo = apps.get_model('Acadimic', 'Promo')
    
    # Get the default promo (created in the previous step)
    default_promo = Promo.objects.first()
    if default_promo:
        # Update all existing semesters to use the default promo
        Semester.objects.filter(promo__isnull=True).update(promo=default_promo)

def reverse_default_promo(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0005_alter_exam_options_exam_section_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promo',
            options={'ordering': ['name', 'speciality']},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['promo__name', 'semester_number']},
        ),
        migrations.AlterModelOptions(
            name='teachermoduleassignment',
            options={'ordering': ['semester', 'module', 'teacher']},
        ),
        migrations.RemoveField(
            model_name='promo',
            name='modules',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='semester',
        ),
        migrations.RunPython(create_default_promo, reverse_default_promo),
        migrations.AddField(
            model_name='semester',
            name='promo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='Acadimic.promo'),
        ),
        migrations.RunPython(update_semester_promo, reverse_default_promo),
        migrations.AddField(
            model_name='semester',
            name='semester_number',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')], default=1),
        ),
        migrations.RunSQL(
            # Forward SQL
            """
            UPDATE "Acadimic_semester" s
            SET semester_number = t.semester_number
            FROM (
                SELECT id,
                       ROW_NUMBER() OVER (PARTITION BY promo_id ORDER BY id) % 2 + 1 as semester_number
                FROM "Acadimic_semester"
            ) t
            WHERE s.id = t.id;
            """,
            # Reverse SQL
            """
            UPDATE "Acadimic_semester" SET semester_number = 1;
            """
        ),
        migrations.AlterField(
            model_name='semester',
            name='promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='Acadimic.promo'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('promo', 'semester_number')},
        ),
        migrations.AddField(
            model_name='semester',
            name='modules',
            field=models.ManyToManyField(blank=True, help_text='Modules taught during this specific semester of the promo.', related_name='semesters', to='Acadimic.versionmodule'),
        ),
        migrations.AddField(
            model_name='teachermoduleassignment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='Acadimic.semester'),
        ),
        migrations.AlterField(
            model_name='teachermoduleassignment',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='Acadimic.versionmodule'),
        ),
        migrations.AlterUniqueTogether(
            name='teachermoduleassignment',
            unique_together={('teacher', 'module', 'semester')},
        ),
        migrations.AlterField(
            model_name='semester',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='semester',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teachermoduleassignment',
            name='promo',
        ),
    ]
