# Generated by Django 5.1.7 on 2025-04-12 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0005_versionmodule_cours_hours_versionmodule_td_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemodule',
            name='description',
        ),
        migrations.RemoveField(
            model_name='versionmodule',
            name='description',
        ),
    ]
