# Generated by Django 5.1.7 on 2025-04-12 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0006_remove_basemodule_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionmodule',
            name='semester',
        ),
        migrations.AddField(
            model_name='promo',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promos', to='Acadimic.semester'),
        ),
        migrations.AddField(
            model_name='promo',
            name='year_end',
            field=models.PositiveIntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promo',
            name='year_start',
            field=models.PositiveIntegerField(default=2023),
            preserve_default=False,
        ),
    ]
