# Generated by Django 5.1.7 on 2025-04-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0007_remove_versionmodule_semester_promo_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='capacity',
        ),
    ]
