# Generated by Django 5.1.7 on 2025-04-12 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0008_remove_classroom_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='Acadimic.classroom'),
        ),
    ]
