# Generated by Django 5.1.7 on 2025-04-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0009_exam_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='type',
            field=models.CharField(choices=[('COURS', 'Course'), ('TD', 'Tutorial Session'), ('TP', 'Practical Session'), ('EXAM', 'Exam')], default='COURS', max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='entry_type',
            field=models.CharField(choices=[('COURS', 'Course'), ('TD', 'Tutorial Session'), ('TP', 'Practical Session'), ('EXAM', 'Exam')], default='COURS', max_length=10),
        ),
    ]
