# Generated by Django 5.1.7 on 2025-04-13 18:51

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0009_remove_semester_promo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['academic_year', 'semester_number']},
        ),
        migrations.RemoveField(
            model_name='semester',
            name='modules',
        ),
        migrations.AddField(
            model_name='academicyear',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicyear',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='year_end',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='year_start',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadimic.academicyear'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_number',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second')]),
        ),
    ]
