# Generated by Django 5.1.7 on 2025-04-12 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0009_exam_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the location (e.g., Building A, Science Faculty, Amphi B)', max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='computers_count',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='has_projector',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='type',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='entry_type',
            field=models.CharField(choices=[('COURSE', 'COURS'), ('TD', 'TD'), ('TP', 'TP'), ('EXAM', 'EXAM')], max_length=10),
        ),
        migrations.AddField(
            model_name='classroom',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Optional location where the classroom is situated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='Acadimic.location'),
        ),
    ]
