# Generated by Django 5.1.7 on 2025-04-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0010_location_alter_classroom_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='has_projector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classroom',
            name='type',
            field=models.CharField(choices=[('COURS', 'Course'), ('TD', 'Tutorial Session'), ('TP', 'Practical Session'), ('EXAM', 'Exam')], default='COURS', max_length=10),
        ),
    ]
