# Generated by Django 5.1.7 on 2025-04-13 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0010_alter_semester_options_remove_semester_modules_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='Acadimic.promo')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'promo')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Acadimic.module')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'module')},
            },
        ),
    ]
