# Generated by Django 5.1.7 on 2025-04-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0010_alter_classroom_type_alter_scheduleentry_entry_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='computers_count',
            new_name='computer_count',
        ),
    ]
