# Generated by Django 5.1.7 on 2025-04-14 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0011_module_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promo',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='promo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='promo',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='Acadimic.academicyear'),
        ),
        migrations.RemoveField(
            model_name='promo',
            name='year_end',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='year_start',
        ),
    ]
