# Generated by Django 5.1.7 on 2025-04-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0011_rename_computers_count_classroom_computer_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='computers_count',
            field=models.IntegerField(default=0),
        ),
    ]
