# Generated by Django 5.1.7 on 2025-04-14 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0012_alter_promo_options_alter_promo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='academic_year',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='Acadimic.academicyear'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='promo',
            unique_together={('name', 'speciality', 'academic_year')},
        ),
    ]
