# Generated by Django 5.1.7 on 2025-04-14 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0013_alter_promo_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='module',
            name='promo',
        ),
        migrations.CreateModel(
            name='PromoModuleSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadimic.versionmodule')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadimic.promo')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadimic.semester')),
            ],
            options={
                'verbose_name': 'Promo Module Assignment (Semester)',
                'verbose_name_plural': 'Promo Module Assignments (Semester)',
                'unique_together': {('promo', 'semester', 'module')},
            },
        ),
        migrations.AddField(
            model_name='promo',
            name='assigned_modules',
            field=models.ManyToManyField(related_name='assigned_promos', through='Acadimic.PromoModuleSemester', to='Acadimic.versionmodule'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
