# Generated by Django 5.1.7 on 2025-04-14 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadimic', '0014_alter_module_unique_together_remove_module_promo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachermoduleassignment',
            options={'ordering': ['teacher', 'module']},
        ),
        migrations.AlterUniqueTogether(
            name='teachermoduleassignment',
            unique_together={('teacher', 'module')},
        ),
        migrations.RemoveField(
            model_name='teachermoduleassignment',
            name='semester',
        ),
        migrations.CreateModel(
            name='TeacherBaseModuleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='Acadimic.basemodule')),
                ('teacher', models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='base_module_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['teacher', 'base_module'],
                'unique_together': {('teacher', 'base_module')},
            },
        ),
    ]
